### ISSUE TITLE
Try to use from tensorboard.plugins.hparams.api.HParam

### ISSUE THREAD

**Issue by Pauladds** [PetrochukM/HParams#1]
I am try to use HParam as:
![Capture](https://user-images.githubusercontent.com/38189240/68375513-462ecf00-0147-11ea-8ef8-88c990dbc1ac.PNG)
where before was tf.contrib.training.HParams, but I have the nextone issue: 
![Capture](https://user-images.githubusercontent.com/38189240/68375609-71192300-0147-11ea-816c-df4ef52bbb75.PNG)
I don't know if is the same that I have before, or I need to replace with something else.
Thank you! :)

**Comment by PetrochukM** [comment]
This is not the same as `tf.contrib.training.HParams`. Please read the README to learn about this repository.
